
linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    shadow: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  depguard:
    rules:
      Main:
        allow:
          - $gostd
          - github.com/aerospike/avs-client-go/protos
          - 'github.com/stretchr/testify/assert'

linters:
  disable-all: true
  enable:
    - bodyclose
#    - unused # intentionally commented to avoid unused func warning as this repo is library
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc # pre-allocate slices with define size if the slice size is known in advance
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - lll
    - wsl # While space linter

run:
  issues-exit-code: 1
  go: '1.21'
#  skip-dirs:
#    - sample
#  skip-files:
#    - sample

issues:
  exclude-rules:
    - path: '(.+)test\.go'
      linters:
      - govet # Test code field alignment for sake of space is not a concern
    - path: 'token_manager_test.go'
      linters:
        - goconst # Test code is allowed to have constants
    - path: 'connection_provider_test.go'
      linters:
        - goconst # Test cod
#     - path: dir/sample\.go
#       linters:
#       - lll # Test code is allowed to have long lines
#     - path: dir/sample\.go
#       linters:
#       - dupl # Test code is allowed to have duplicate code
#     - path: dir/sample\.go
#       linters:
#       - dupl # Test code is allowed to have duplicate code
#     - linters:
#         - lll
#       source: "// "
