services:
  aerospike:
    image: aerospike/aerospike-server-enterprise:7.0.0.2
    # ports:
    #   - "3000:3000"
    volumes:
      - ./config/aerospike.conf:/opt/aerospike/etc/aerospike/aerospike.conf
      - ./config/features.conf:/opt/aerospike/etc/aerospike/features.conf
    command:
      - "--config-file"
      - "/opt/aerospike/etc/aerospike/aerospike.conf"
    healthcheck:
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 1s
      timeout: 20s
      retries: 20
    networks:
      - avs-demo
  avs-1:
    depends_on:
      aerospike:
        condition: service_healthy
    image: aerospike/aerospike-vector-search:0.10.0
    volumes:
      - ./config/aerospike-vector-search-1.yml:/etc/aerospike-vector-search/aerospike-vector-search.yml
      - ./config/features.conf:/etc/aerospike-vector-search/features.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://avs-1:5040/manage/rest/v1"]
      interval: 1s
      timeout: 20s
      retries: 20
    networks:
      - avs-demo
  avs-2:
    depends_on:
      aerospike:
        condition: service_healthy
    image: aerospike/aerospike-vector-search:0.10.0
    volumes:
      - ./config/aerospike-vector-search-2.yml:/etc/aerospike-vector-search/aerospike-vector-search.yml
      - ./config/features.conf:/etc/aerospike-vector-search/features.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://avs-2:5040/manage/rest/v1"]
      interval: 1s
      timeout: 20s
      retries: 20
    networks:
      - avs-demo
  avs-3:
    depends_on:
      aerospike:
        condition: service_healthy
    image: aerospike/aerospike-vector-search:0.10.0
    volumes:
      - ./config/aerospike-vector-search-3.yml:/etc/aerospike-vector-search/aerospike-vector-search.yml
      - ./config/features.conf:/etc/aerospike-vector-search/features.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://avs-3:5040/manage/rest/v1"]
      interval: 1s
      timeout: 20s
      retries: 20
    networks:
      - avs-demo
  nginx:
    image: nginx:latest
    ports:
      - "10000:10000"
    depends_on:
      avs-1:
        condition: service_healthy
      avs-2:
        condition: service_healthy
      avs-3:
        condition: service_healthy
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - avs-demo

networks:
  avs-demo: {}