// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: transact.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactClient is the client API for Transact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactClient interface {
	// Update/insert records.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get a record.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Record, error)
	// Delete a record.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Check if a record exists.
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*Boolean, error)
	// Check is a record is indexed.
	IsIndexed(ctx context.Context, in *IsIndexedRequest, opts ...grpc.CallOption) (*Boolean, error)
	// Perform a vector nearest neighbor search.
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (Transact_VectorSearchClient, error)
}

type transactClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactClient(cc grpc.ClientConnInterface) TransactClient {
	return &transactClient{cc}
}

func (c *transactClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aerospike.vector.Transact/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/aerospike.vector.Transact/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aerospike.vector.Transact/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/aerospike.vector.Transact/Exists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) IsIndexed(ctx context.Context, in *IsIndexedRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/aerospike.vector.Transact/IsIndexed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (Transact_VectorSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Transact_ServiceDesc.Streams[0], "/aerospike.vector.Transact/VectorSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactVectorSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Transact_VectorSearchClient interface {
	Recv() (*Neighbor, error)
	grpc.ClientStream
}

type transactVectorSearchClient struct {
	grpc.ClientStream
}

func (x *transactVectorSearchClient) Recv() (*Neighbor, error) {
	m := new(Neighbor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactServer is the server API for Transact service.
// All implementations must embed UnimplementedTransactServer
// for forward compatibility
type TransactServer interface {
	// Update/insert records.
	Put(context.Context, *PutRequest) (*emptypb.Empty, error)
	// Get a record.
	Get(context.Context, *GetRequest) (*Record, error)
	// Delete a record.
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// Check if a record exists.
	Exists(context.Context, *ExistsRequest) (*Boolean, error)
	// Check is a record is indexed.
	IsIndexed(context.Context, *IsIndexedRequest) (*Boolean, error)
	// Perform a vector nearest neighbor search.
	VectorSearch(*VectorSearchRequest, Transact_VectorSearchServer) error
	mustEmbedUnimplementedTransactServer()
}

// UnimplementedTransactServer must be embedded to have forward compatible implementations.
type UnimplementedTransactServer struct {
}

func (UnimplementedTransactServer) Put(context.Context, *PutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTransactServer) Get(context.Context, *GetRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTransactServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTransactServer) Exists(context.Context, *ExistsRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedTransactServer) IsIndexed(context.Context, *IsIndexedRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsIndexed not implemented")
}
func (UnimplementedTransactServer) VectorSearch(*VectorSearchRequest, Transact_VectorSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedTransactServer) mustEmbedUnimplementedTransactServer() {}

// UnsafeTransactServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactServer will
// result in compilation errors.
type UnsafeTransactServer interface {
	mustEmbedUnimplementedTransactServer()
}

func RegisterTransactServer(s grpc.ServiceRegistrar, srv TransactServer) {
	s.RegisterService(&Transact_ServiceDesc, srv)
}

func _Transact_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.Transact/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.Transact/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.Transact/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.Transact/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_IsIndexed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsIndexedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).IsIndexed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.Transact/IsIndexed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).IsIndexed(ctx, req.(*IsIndexedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_VectorSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VectorSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactServer).VectorSearch(m, &transactVectorSearchServer{stream})
}

type Transact_VectorSearchServer interface {
	Send(*Neighbor) error
	grpc.ServerStream
}

type transactVectorSearchServer struct {
	grpc.ServerStream
}

func (x *transactVectorSearchServer) Send(m *Neighbor) error {
	return x.ServerStream.SendMsg(m)
}

// Transact_ServiceDesc is the grpc.ServiceDesc for Transact service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transact_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aerospike.vector.Transact",
	HandlerType: (*TransactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Transact_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Transact_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Transact_Delete_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _Transact_Exists_Handler,
		},
		{
			MethodName: "IsIndexed",
			Handler:    _Transact_IsIndexed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VectorSearch",
			Handler:       _Transact_VectorSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transact.proto",
}
