// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: transact.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactServiceClient is the client API for TransactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactServiceClient interface {
	// Update/insert records.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get a record.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Record, error)
	// Delete a record.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Check if a record exists.
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*Boolean, error)
	// Check is a record is indexed.
	IsIndexed(ctx context.Context, in *IsIndexedRequest, opts ...grpc.CallOption) (*Boolean, error)
	// Perform a vector nearest neighbor search.
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (TransactService_VectorSearchClient, error)
}

type transactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactServiceClient(cc grpc.ClientConnInterface) TransactServiceClient {
	return &transactServiceClient{cc}
}

func (c *transactServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aerospike.vector.TransactService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Record, error) {
	out := new(Record)
	err := c.cc.Invoke(ctx, "/aerospike.vector.TransactService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/aerospike.vector.TransactService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactServiceClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/aerospike.vector.TransactService/Exists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactServiceClient) IsIndexed(ctx context.Context, in *IsIndexedRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := c.cc.Invoke(ctx, "/aerospike.vector.TransactService/IsIndexed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactServiceClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (TransactService_VectorSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactService_ServiceDesc.Streams[0], "/aerospike.vector.TransactService/VectorSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactServiceVectorSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactService_VectorSearchClient interface {
	Recv() (*Neighbor, error)
	grpc.ClientStream
}

type transactServiceVectorSearchClient struct {
	grpc.ClientStream
}

func (x *transactServiceVectorSearchClient) Recv() (*Neighbor, error) {
	m := new(Neighbor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactServiceServer is the server API for TransactService service.
// All implementations must embed UnimplementedTransactServiceServer
// for forward compatibility
type TransactServiceServer interface {
	// Update/insert records.
	Put(context.Context, *PutRequest) (*emptypb.Empty, error)
	// Get a record.
	Get(context.Context, *GetRequest) (*Record, error)
	// Delete a record.
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// Check if a record exists.
	Exists(context.Context, *ExistsRequest) (*Boolean, error)
	// Check is a record is indexed.
	IsIndexed(context.Context, *IsIndexedRequest) (*Boolean, error)
	// Perform a vector nearest neighbor search.
	VectorSearch(*VectorSearchRequest, TransactService_VectorSearchServer) error
	mustEmbedUnimplementedTransactServiceServer()
}

// UnimplementedTransactServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransactServiceServer struct {
}

func (UnimplementedTransactServiceServer) Put(context.Context, *PutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedTransactServiceServer) Get(context.Context, *GetRequest) (*Record, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTransactServiceServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTransactServiceServer) Exists(context.Context, *ExistsRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedTransactServiceServer) IsIndexed(context.Context, *IsIndexedRequest) (*Boolean, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsIndexed not implemented")
}
func (UnimplementedTransactServiceServer) VectorSearch(*VectorSearchRequest, TransactService_VectorSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedTransactServiceServer) mustEmbedUnimplementedTransactServiceServer() {}

// UnsafeTransactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactServiceServer will
// result in compilation errors.
type UnsafeTransactServiceServer interface {
	mustEmbedUnimplementedTransactServiceServer()
}

func RegisterTransactServiceServer(s grpc.ServiceRegistrar, srv TransactServiceServer) {
	s.RegisterService(&TransactService_ServiceDesc, srv)
}

func _TransactService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.TransactService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.TransactService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.TransactService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.TransactService/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServiceServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactService_IsIndexed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsIndexedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServiceServer).IsIndexed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aerospike.vector.TransactService/IsIndexed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServiceServer).IsIndexed(ctx, req.(*IsIndexedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactService_VectorSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VectorSearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactServiceServer).VectorSearch(m, &transactServiceVectorSearchServer{stream})
}

type TransactService_VectorSearchServer interface {
	Send(*Neighbor) error
	grpc.ServerStream
}

type transactServiceVectorSearchServer struct {
	grpc.ServerStream
}

func (x *transactServiceVectorSearchServer) Send(m *Neighbor) error {
	return x.ServerStream.SendMsg(m)
}

// TransactService_ServiceDesc is the grpc.ServiceDesc for TransactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aerospike.vector.TransactService",
	HandlerType: (*TransactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _TransactService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TransactService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TransactService_Delete_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _TransactService_Exists_Handler,
		},
		{
			MethodName: "IsIndexed",
			Handler:    _TransactService_IsIndexed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "VectorSearch",
			Handler:       _TransactService_VectorSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transact.proto",
}
